plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.MurmuDevelopers.Shayaari'
    compileSdk 36

    defaultConfig {
        applicationId "com.MurmuDevelopers.Shayaari"
        minSdk 24
        targetSdk 36
        versionCode 4
        versionName "4.3"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.navigation.ui
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.espresso.intents
    implementation libs.circleimageview
    implementation libs.gson
    implementation libs.material.v140
    implementation libs.coordinatorlayout

}